apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  labels:
    app: production-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production-deployment
  template:
    metadata:
      labels:
        app: production-deployment
    spec:
      containers:
      - name: production-deployment
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-02-67974c662b31/my-repository/sample-app:v1.0
        ports:
        - containerPort: 8080
